server:
  port: 8181
spring:
  profiles: development
  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:postgresql://172.30.184.113:5434/postgres
    username: postgres
    password: nsdl1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50

    # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create
      show-sql: false
      
      ########TO DO -> SC